name: CI

on: pull_request

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - run: npm ci

      - run: npm run lint

  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Build the image
        run: docker build -t iperf .

      - name: Run the iperf as server
        run: |
          docker run --name iperf-server --rm --detach --publish 5201:5201 iperf

      - id: network
        run: |
          [[ $(ip -4 addr show dev eth0 | grep "inet") =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})/[0-9]{1,2} ]]
          echo "::set-output name=ipaddr::${BASH_REMATCH[1]}"

      - name: Test the iperf connection
        run: |
          docker run --name iperf-client --rm iperf -c ${{ steps.network.outputs.ipaddr }} -t 1

      - name: Stop the iperf server
        if: ${{ always() }}
        run: docker stop iperf-server
